---
title: "p8105_hw5_hc3451"
author: "Huanyu Chen"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
library(tibble)
library(broom)
library(tidyverse)
library(ggplot2)
set.seed(1)
```

# Problem 3
## (1) mu = 0

```{r}
t_test = function(n, mu = 0, sigma = 5) {
  sim_data <- tibble(
    x = rnorm(n, mean = mu, sd = sigma)
    )
  t_test_results <- broom::tidy(t.test(sim_data))
  
  t_test_results |> 
    select(estimate, p.value)
}

sim_t_result <- tibble(
  sample_size = 30,
  iter = 1:5000
) |>
  mutate(estimate_t_test = map(sample_size, t_test)) |>
  unnest(estimate_t_test)
```

## (2) mu = 1,2,3,4,5,6
```{r}
t_test = function(mu, sigma = 5) {
  sim_data <- tibble(
    x = rnorm(30, mean = mu, sd = sigma)
    )
  t_test_results <- broom::tidy(t.test(sim_data))
  
  t_test_results |> 
    select(estimate, p.value)
}

sim_t_result_1 =
  expand_grid(
    mu_values = c(1, 2, 3, 4, 5, 6),
    iter = 1:5000
  ) |> 
  mutate(estimate_t_test = map(mu_values, t_test)) |>
  unnest(estimate_t_test) |>
  group_by(mu_values) |>
  summarise(estimate = mean(estimate), power = mean(p.value< 0.05))
```

## Graph
```{r}
ggplot(sim_t_result_1, aes(x = mu_values, y = power)) +
  geom_line() +
  labs(x = "True Value of Mean", y = "Power of the Test") +
  ggtitle("Power of the Test vs. True Value of Mean")
```

```{r}
ggplot(sim_t_result_1, aes(x = mu_values, y = estimate)) +
  geom_line() +
  labs(x = "True Value of Mean", y = "Average Estimate of Mean") +
  ggtitle("Average Estimate of Mean vs. True Value of Mean")
```

```{r}
sim_t_result_2 = 
  expand_grid(
    mu_values = c(1, 2, 3, 4, 5, 6),
    iter = 1:5000
  ) |> 
  mutate(estimate_t_test = map(mu_values, t_test)) |>
  unnest(estimate_t_test) |>
  group_by(mu_values) |>
  filter(p.value > 0.05) |>
  summarise(estimate = mean(estimate))

ggplot(sim_t_result_2, aes(x = mu_values, y = estimate)) +
  geom_line() +
  labs(x = "True Value of Mean", y = "Average Estimate of Mean (when null was rejected)") +
  ggtitle("Average Estimate of Mean (when null was rejected) vs. True Value of Mean")
```
The sample average of mean across tests for which the null is rejected is not approximately equal to the true value of mean. By this way, the null will be rejected under the confidence interval.
